AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes


Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'scripts/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'scripts/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'scripts/**/*'

Layout/LineLength:
  Max: 800
  Exclude:
    - 'lib/services/optimized_image_service.rb'

Style/HashLikeCase:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

# Allow debug statements in test files (intentional for troubleshooting)
Lint/Debugger:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

# Allow duplicate branch in error handling (different contexts)
Lint/DuplicateBranch:
  Enabled: false

# Relax some complexity metrics for DTOs and error handlers
Naming/VariableNumber:
  Enabled: false

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'scripts/**/*'
    - 'lib/controllers/**/*'
    - 'lib/dto/**/*'

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - 'scripts/**/*'
    - 'lib/controllers/**/*'
    - 'lib/dto/**/*'

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - 'scripts/**/*'
    - 'lib/controllers/**/*'
    - 'lib/dto/**/*'

Metrics/ModuleLength:
  Max: 200