AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes


Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'scripts/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'scripts/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'scripts/**/*'

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - 'scripts/**/*'

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'scripts/**/*'

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'scripts/**/*'

Metrics/ModuleLength:
  Max: 150

Layout/LineLength:
  Max: 800
  Exclude:
    - 'lib/services/optimized_image_service.rb'

Style/HashLikeCase:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false